@startuml simple-test

rectangle "Customer" as customer
rectangle "Banking System" as banking [[02-container.svg]]
rectangle "Mainframe" as mainframe

customer --> banking : Uses HTTPS
banking --> mainframe : Gets data

note right of banking : Click to see containers

@enduml